/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterTaxRouteImport } from './routes/master.tax'
import { Route as MasterPlanRouteImport } from './routes/master.plan'
import { Route as CustomersSubscriptionRouteImport } from './routes/customers.subscription'
import { Route as CustomersCustomerRouteImport } from './routes/customers.customer'

const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterTaxRoute = MasterTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPlanRoute = MasterPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => MasterRoute,
} as any)
const CustomersSubscriptionRoute = CustomersSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersCustomerRoute = CustomersCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/customers/customer': typeof CustomersCustomerRoute
  '/customers/subscription': typeof CustomersSubscriptionRoute
  '/master/plan': typeof MasterPlanRoute
  '/master/tax': typeof MasterTaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/customers/customer': typeof CustomersCustomerRoute
  '/customers/subscription': typeof CustomersSubscriptionRoute
  '/master/plan': typeof MasterPlanRoute
  '/master/tax': typeof MasterTaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/customers/customer': typeof CustomersCustomerRoute
  '/customers/subscription': typeof CustomersSubscriptionRoute
  '/master/plan': typeof MasterPlanRoute
  '/master/tax': typeof MasterTaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/master'
    | '/customers/customer'
    | '/customers/subscription'
    | '/master/plan'
    | '/master/tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/master'
    | '/customers/customer'
    | '/customers/subscription'
    | '/master/plan'
    | '/master/tax'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/master'
    | '/customers/customer'
    | '/customers/subscription'
    | '/master/plan'
    | '/master/tax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/tax': {
      id: '/master/tax'
      path: '/tax'
      fullPath: '/master/tax'
      preLoaderRoute: typeof MasterTaxRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/plan': {
      id: '/master/plan'
      path: '/plan'
      fullPath: '/master/plan'
      preLoaderRoute: typeof MasterPlanRouteImport
      parentRoute: typeof MasterRoute
    }
    '/customers/subscription': {
      id: '/customers/subscription'
      path: '/subscription'
      fullPath: '/customers/subscription'
      preLoaderRoute: typeof CustomersSubscriptionRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/customer': {
      id: '/customers/customer'
      path: '/customer'
      fullPath: '/customers/customer'
      preLoaderRoute: typeof CustomersCustomerRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerRoute: typeof CustomersCustomerRoute
  CustomersSubscriptionRoute: typeof CustomersSubscriptionRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerRoute: CustomersCustomerRoute,
  CustomersSubscriptionRoute: CustomersSubscriptionRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface MasterRouteChildren {
  MasterPlanRoute: typeof MasterPlanRoute
  MasterTaxRoute: typeof MasterTaxRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterPlanRoute: MasterPlanRoute,
  MasterTaxRoute: MasterTaxRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
